default_environment: default
environments:
    default:
        connections:
            google_cloud_platform:
                - name: gcp
                  project_id: ecommerce-analytics-bruin
                  service_account_json: $GCP_SERVICE_ACCOUNT_KEY
